
$mostlyopaque
$illumposition	0 0 80
$modelname		jessev92/bf2142/weapons/parachute_w
$model	BF3		bf2142_w
$cdmaterials	models/jessev92/bf2142
$cdmaterials	models/jessev92/bf2142/items
$cdmaterials	models/jessev92/bf2142/weapons
$surfaceprop	carpet
$contents		solid
$hboxset		default
$sequence	idle	bf2142_w	{	fps	1	}
$collisionmodel	bf2142_w	{
	$mass 5.0
	$inertia 1.00
	$damping 0.00
	$rotdamping 0.00
}
