
$mostlyopaque
$illumposition	0 0 80
$modelname		jessev92/bf3/items/parachute
$model	BF3		bf3_w_chute
$cdmaterials	models/jessev92/bf3
$cdmaterials	models/jessev92/bf3/items
$cdmaterials	models/jessev92/bf3/items/parachute
$cdmaterials	models/jessev92/bf3/weapons
$cdmaterials	models/jessev92/bf3/weapons/parachute
$surfaceprop	carpet
$contents		solid
$hboxset		default
$sequence	idle	bf3_w_chute	{	fps	1	}
$collisionmodel	bf3_w_chute	{
	$mass 5.0
	$inertia 1.00
	$damping 0.00
	$rotdamping 0.00
}
