$cd "F:\0-mdl\Decompiled_Props\gta_parachute_pack"
$modelname "GTA IV/Parachute_pack.mdl"
$model "studio" "chute.smd"
$cdmaterials "models\Jason278\GTA IV\"
$hboxset "default"
// Model uses material "sus2_diff_001_a_uni.vmt"
$surfaceprop "plastic"
$keyvalues  { prop_data { "base" "metal.Small"  } } 
$illumposition -2.898 -0.382 1.720
$sequence idle "idle" fps 1.00
$collisionmodel "phymodel.smd" {

	$concave
	$mass 1500.0
	$inertia 1.00
	$damping 0.00
	$rotdamping 0.00
}
